### ISSUE TITLE
winwal should error better when ran on WindowsPowerShell

### ISSUE THREAD

**Issue by codemeatloaf** [scaryrawr/winwal#3]
Whenever i run
"> Update-WalTheme -Image '.\OneDrive\wallpapers\Simon Stalenhag\10.jpg'"

This is the output i get and nothing changes:
![Capture](https://user-images.githubusercontent.com/65986665/111571675-e3494f80-87f2-11eb-8df8-c3445bfe8b6c.PNG)

**Comment by codemeatloaf** [comment]
Fixed it! Just had to update to Powershell 7, my bad!

**Comment by scaryrawr** [comment]
I think there should be a check to warn on older versions of PowerShell. Re-opening.
